name: iSUS API
on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: isus_testing
        ports:
          - 33306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Update composer
        run: sudo composer self-update
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Check PHP CS
        run: composer run php-cs:check
      - name: Run migrations
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: isus_testing
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: 12345678
          DB_CONNECTION_TEST: mysql
          DB_DATABASE_TEST: isus_testing
          DB_PORT_TEST: 33306
          DB_USER_TEST: root
          DB_PASSWORD_TEST: 12345678
        run: php artisan migrate
     # - name: Run tests
     #   run: php artisan test
